version: '3'
services:
  api-server:
    restart: always
    depends_on: 
      - mongo
    build: ./api-server
    ports:
      - 8000:8000
  app-server:
    restart: always
    depends_on: 
      - mongo
      - api-server
    build: ./app-server
    ports:
      - 3000:3000
  mongo:
    image: mongo
    # ports:
    #   - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
 mongodb:
